### ISSUE TITLE
3D view of electron doesn't update in downstream sim when setting state the second time

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/models-of-the-hydrogen-atom#164]
**Test device**
MacBook Air (M1 chip)

**Operating System**
15.3.2

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/1225, on either screen, in the State wrapper:

With the 3D view of the deBroglie model selected, if I pause the sim and press Set State Now, it looks correct in the downstream sim. If I wait until the electron is in a different energy level in the upstream sim, press pause and press Set State now, the n value has updated but the electron is in the wrong energy level. Pressing play fixes the issue.

**Steps to reproduce**
1. In the state wrapper set state rate =0
2. In the upstream sim: select Energy Levels Screen
3. Turn on the light
4. Select de Broglie and then 3D view
5. Press pause
6. Press Set State Now
7. In the downstream sim press Play
8. In the upstream sim press Play
9. Pause sim when the electron is in a different energy level than the first time around
10. Press Set State Now

**Visuals**

https://github.com/user-attachments/assets/ebc426d8-a30d-4e41-ac97-98e443e33fdb

**Comment by pixelzoom** [comment]
Reproduced in main.   Pressing the step button (advancing the sim 1 tilmestep) also fixes the issue.

**Comment by pixelzoom** [comment]
It's odd that this does not occur with the other 2 de Broglie views (Brightness, Radial Distance).

**Comment by pixelzoom** [comment]
Fixed in main and 1.0 in the above commits. 

@Nancy-Salpepi please verifiy in main. If it looks OK, change the issue label to "fixed-awaiting-deploy", for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Looks fixed on main 🙂.

**Comment by pixelzoom** [comment]
Ready for review in https://github.com/phetsims/qa/issues/1238. If it looks OK, please close.

**Comment by Nancy-Salpepi** [comment]
Sorry I didn't see this the first time @pixelzoom. The electron in the atom is correct, but the Energy Level Diagram is incorrect. Follow the first 6 steps in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issue-2980810759. 
I confirmed that this didn't happen in rc.1.

<img width="538" alt="Image" src="https://github.com/user-attachments/assets/21271873-1fee-41fd-8ba9-25bfbacc54ec" />

**Comment by Nancy-Salpepi** [comment]
For the Schrödinger model in both rc.1 and rc.2, when setting state you only see the electron in the Energy Level Diagram and not the transition no matter which direction the electron is transitioniing. 

<img width="538" alt="Image" src="https://github.com/user-attachments/assets/db448627-0a70-4265-b258-d6b7ff306922" />

**Comment by Nancy-Salpepi** [comment]
For both the deBroglie and  Bohr model, it works correctly if the first time I set state the electron was moving to a higher energy level and the second time I set state it was moving to a lower energy level. 

@pixelzoom should the transition be included when setting state or should we only show the electron in the correct energy level?

**Comment by pixelzoom** [comment]
It will be problematic to show the transition when setting state. To draw the transition arrow correctly we need to know the previous electron state. That determines where the tail of the arrow is, and the direction of the arrow.  Since the previous electron state is not included in PhET-iO state, I think we'll have to forgo showing the transition arrow.

**Comment by pixelzoom** [comment]
As @Nancy-Salpepi noticed, we do not show the transition squiggle for Schrodinger when setting state, because the electron state change may be invalid and cause the sim to error - see https://github.com/phetsims/models-of-the-hydrogen-atom/issues/111.   In https://github.com/phetsims/models-of-the-hydrogen-atom/commit/afc698d12c4dbfbc95cb23d77af1a3b8df95de5e, I've implemented something similar for Bohr and de Broglie models. When PhET-iO state is set, no transition squiggle is shown.

@Nancy-Salpepi please review in main.  If this looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
@pixelzoom I still get the transition squiggle if I happen to set state when the electron in the downstream sim is in the same energy level as the electron in the upstream sim. 

Steps:
1. In the State wrapper, select Energy Levels Screen
2. Turn on the light
3. Set State Rate = 0
4. Pause upstream sim when electron is transitioning back down and is at n=2
5. Press Set State Now when electron in the downstream sim is at n=2 (but has followed a different path than upstream sim)

<img width="419" alt="Image" src="https://github.com/user-attachments/assets/9b5288f1-40d7-41ab-a215-de9582c3b696" />

<img width="525" alt="Image" src="https://github.com/user-attachments/assets/94f6282c-af98-41a5-a22e-a2bc77727999" />

**Comment by pixelzoom** [comment]
@Nancy-Salpepi I'm having some difficulty reproducing this.  Are there some steps missing from https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2796927883?  Did you interact with the Downstream sim between steps 4 & 5?  Is the Downstream sim running or paused at the point when step 5 occurs?

**Comment by Nancy-Salpepi** [comment]
I did have a raging fever when I was looking at this....let me see...

**Comment by Nancy-Salpepi** [comment]
I didn't even get to check those steps because it is happening so easily for me right now. I'm using rc.2. version on mac + safari. 
1. State wrapper, set state rate =0
2. Upstream sim: Open Energy Levels screen
3. Turn on light
4. Pause sim as electron makes its way back down (but not at n=1)
5. Press set state now.

**Comment by Nancy-Salpepi** [comment]
Weird that in rc.2 I don't see the behavior I described in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2796927883 at the moment. I do see it on main though. 
I fixed the steps in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2796927883.
I was definitely delirious.

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  Another question... Does this also occur with de Broglie or Schrodinger, or does it seem to be specific to Bohr?

**Comment by Nancy-Salpepi** [comment]
Bohr and de Broglie

**Comment by pixelzoom** [comment]
Fixed in main and 1.0 branches.

I was a little confused about why this is occurring in Bohr and de Broglie, but not in Schrodinger.  All 3 are using the same implementation pattern to decide when to hide the squiggle.  But I think I've convinced myself that it's not occurring in Schrodinger because the (n,l,m) state is an Object, so if the electron is in (for example) state (1,0,0), and update will still occur when the state engine sets (1,0,0) because that will be a new Object instance. If we were using deep equality it would not update, but we are using referential equality.  That said...

I've updated all 3 models, so that they continue to use the same implementation pattern.  The new pattern is to _always_ hide the squiggle immediately after the PhET-iO engine has finished setting state (versus in response to a change in electron state), because the state transition is likely to be invalid.  I've tested with the steps in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2796927883, and this appears to address the problem. 

@Nancy-Salpepi This is ready for review.  Note that there were no changes related to the original problem reported in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issue-2980810759, so you only need to test the problem with the "squiggle" in the Energy diagrams. But you do need to test it for all 3 models.

If this looks OK, please change the issue label to "fixed-awaiting-deploy".

**Comment by Nancy-Salpepi** [comment]
Things look squiggle-free in the downstream sim. 🤞🏻 I didn't miss anything.

**Comment by pixelzoom** [comment]
Please verify in https://github.com/phetsims/qa/issues/1243 (1.0.0-rc.3).

The first issue involves the de Broglie '3D Height' view, and is described in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issue-2980810759.  It was verified in https://github.com/phetsims/qa/issues/1238, and there have been no changes to related code since then. So you do not need to verify that issue, but by all means do so if you'd like.

The second issue involves the Energy diagram, and there are 2 sets of steps: https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2792407916, https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2796927883.  It is sufficient to verify on 1 platforn.

**Comment by zepumph** [comment]
I'm going to take a little bit of a look here.

**Comment by KatieWoe** [comment]
I also saw it using the steps in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2813406528, but the electron was transitioning from 1 to 3, up rather than down.

**Comment by KatieWoe** [comment]
Actually, this happens in the main sim, without the state wrapper. 
Steps:
1. Go to Energy Levels Screen
2. Turn on light
3. Wait for electron to transition up
4. Pause sim
5. Switch from model to experiment then back

Visuals

![Image](https://github.com/user-attachments/assets/9241c298-ec64-44ce-aedd-348db511deb9)

**Comment by pixelzoom** [comment]
Fixed in main and 1.0 in the above commits. @Nancy-Salpepi ready for review. As @KatieWoe mentioned, this can be reproduced in the PhET brand, so feel free to verify in either or both brands.  If it looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Unfortunately, now we are back to having an issue with the 3D Height representation of the de Broglie electron. In the PhET brand sim, if I switch while paused from the de Broglie model to another model and then back again, the electron does not reset to n=1.

Steps:
1. On either screen, select de Broglie model
2. Change the view to 3D Height
3. Turn on the light
4. Pause the sim when the electron is at any n value aside from 1
5. Select another model
6. Select the de Broglie model

<img width="1059" alt="Image" src="https://github.com/user-attachments/assets/2c0537bb-3567-40c7-b190-d08d50c32329" />

**Comment by Nancy-Salpepi** [comment]
A second issue: I still see the squiggle if the spectrometer is open and data has been collected. 

Steps:
1. In the PhET brand sim, go to the Energy Levels screen
2. Open the Spectrometer 
3. Turn on the light
4. Pause the sim once a data point in the UV or IR range appears in the Spectrometer and a squiggle is present in the Electron Energy Level diagram
5. Either switch to a different Model or switch to Experiment
6. Switch back to the Bohr model

What is weird is, the bug doesn't happen if the data point was in the visible spectrum (at least not that I saw). 
This bug also happens with de Broglie. I didn't see it with Schrödinger.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2815309559 is not a new problem with de Broglie "3D Height". It was present as far back as [1.0.0-rc.1](https://phet-dev.colorado.edu/html/models-of-the-hydrogen-atom/1.0.0-rc.1/phet/models-of-the-hydrogen-atom_en_phet.html).  I'm going to move it to a new issue, because it's not related to either of the problems being discussed in this issue, and I don't want to further complicate this issue.

**Comment by pixelzoom** [comment]
For https://github.com/phetsims/models-of-the-hydrogen-atom/issues/164#issuecomment-2815343735 ...

I also don't need to have the Spectrometer open to reproduce this in main.

This is also not a new problem, present as far back as [1.0.0-rc.1](https://phet-dev.colorado.edu/html/models-of-the-hydrogen-atom/1.0.0-rc.1/phet/models-of-the-hydrogen-atom_en_phet.html).  It's not related to the original problem reported for '3D Height' in this issue, and it's not related to the 2nd State wrapper problem that was reported for the energy squiggles.  So I'm also going to move this to new issue https://github.com/phetsims/models-of-the-hydrogen-atom/issues/166.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi I've moved the 2 new issues that you've reported to separate issues.  Do you feel like I've address the original 2 issues that were reported herein?  If so, please close this issue.

**Comment by Nancy-Salpepi** [comment]
The original issues look fixed on main. Closing this.
